### PR TITLE
Fixed retrieving large amounts of existing event log entires with Ora…

### LINKED ISSUE #6: Retrieving existing event log entries fails with Oracle when list of content hashes is over 1000

### PR DESCRIPTION
**Pull request by TimovanderKamp**
…cle.

Resolves: #6

### CODE REVIEW

**Review by fatihict — APPROVED** [review]

File: src/avisi/crux/active_objects.clj [hunk 1]
```diff
@@ -101,8 +101,12 @@
                                      (conj m [(str (c/new-id doc)) doc]))
                                    []
                                    docs)
+          docs-batches (partition-all 500 (mapv first docs-with-hashes))
           existing (group-by #(.getKey ^EventLogEntry %)
-                             (get-existing-event-log-entries ao (mapv first docs-with-hashes)))]
+                             (reduce (fn [existing-entries docs-batch]
```
Comment (mitchelkuijpers) [inline src/avisi/crux/active_objects.clj]: je kan hier `mapcat` ipv `reduce` gebruiken

**Review by mitchelkuijpers — CHANGES_REQUESTED** [review]

**Review by mitchelkuijpers — APPROVED** [review]
